# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  backendfoodxhangeapi:
    image: backendfoodxhangeapi
    build:
      context: .
      dockerfile: src/Backend.Foodxhange.Api/Dockerfile
    ports:
      - 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
