name: build image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  image-name: ghcr.io/mjmacheli/dotnet-be:${{ github.sha }}

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . -t ${{ env.image-name }}

      - name: Scan image
        uses: azure/container-scan@v0
        with:
          image-name: ${{ env.image-name }}
          severity-threshold: MEDUM
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_R }}
      
      - name: Login to gh docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_R }}

      - name: Docker push to registrty
        run: docker push ${{ env.image-name }}

      
